## 文のベクトル表現

### 例題2.5

In [7]:
from collections import Counter
from numpy.linalg import norm
import numpy as np

s1 = "the pen is mightier than the sword".split()
s2 = "the sword is mightier than the pen".split()

keys = list(set(s1 + s2))

counter_s1 = Counter(s1)
counter_s2 = Counter(s2)

bow_s1 = np.array([counter_s1[key] if counter_s1[key] else 0 for key in keys])
bow_s2 = np.array([counter_s2[key] if counter_s2[key] else 0 for key in keys])

print("bag-of-words of s1:")
print(bow_s1)
print("bag-of-words of s2:")
print(bow_s2)

bag-of-words of s1:
[1 1 2 1 1 1]
bag-of-words of s2:
[1 1 2 1 1 1]


In [9]:
sim_bow = bow_s1.dot(bow_s2) / (norm(bow_s1) * norm(bow_s2))
print("sim_cos(s1, s2) of bag-of-words:")
print(sim_bow)

sim_cos(s1, s2) of bag-of-words:
1.0


In [8]:
keys = list(set(list(zip(s1, s1[1:])) + list(zip(s2, s2[1:]))))

counter_s1 = Counter(list(zip(s1, s1[1:])))
counter_s2 = Counter(list(zip(s2, s2[1:])))

bobi_s1 = np.array([counter_s1[key] if counter_s1[key] else 0 for key in keys])
bobi_s2 = np.array([counter_s2[key] if counter_s2[key] else 0 for key in keys])

print("bag-of-bigrams of s1:")
print(bobi_s1)
print("bag-of-bigrams of s2:")
print(bobi_s2)

bag-og-bigrams of s1:
[1 1 1 0 1 1 1]
bag-og-bigrams of s2:
[1 1 0 1 1 1 1]


In [10]:
sim_bobi = bobi_s1.dot(bobi_s2) / (norm(bobi_s1) * norm(bobi_s2))
print("sim_cos(s1, s2) of bag-of-bigrams:")
print(sim_bobi)

sim_cos(s1, s2) of bag-of-bigrams:
0.833333333333


### 例題2.6

In [28]:
from functools import reduce
import re

s1 = re.sub(r'[\.,?]', "", "A cat sat on the mat.").lower().split(" ")
s2 = re.sub(r'[\.,?]', "", "Cats are sitting on the mat.").lower().split(" ")

def vectorize_with_bow(*sentences):
    keys = sorted(set(reduce(lambda x, y: x + y, sentences)))
    counters = [Counter(sentence) for sentence in sentences]
    return [np.array([c[key] if c[key] else 0 for key in keys]) for c in counters]

def sim_cos(lhs, rhs):
    return lhs.dot(rhs) / norm(lhs) / norm(rhs)
    
bow_s1, bow_s2 = vectorize_with_bow(s1, s2)
print("bow of s1:")
print(bow_s1)
print("bow of s2:")
print(bow_s2)
print("sim_cos(s1, s2):")
print(sim_cos(bow_s1, bow_s2))

bow of s1:
[1 0 1 0 1 1 1 0 1]
bow of s2:
[0 1 0 1 1 1 0 1 1]
sim_cos(s1, s2):
0.5


In [29]:
lemmatizated_s1 = "a cat sit on the mat".split(" ")
lemmatizated_s2 = "cat are sit on the mat.".split(" ")
bow_s1, bow_s2 = vectorize_with_bow(lemmatizated_s1, lemmatizated_s2)
print("bow of s1:")
print(bow_s1)
print("bow of s2:")
print(bow_s2)
print("sim_cos(s1, s2):")
print(sim_cos(bow_s1, bow_s2))

bow of s1:
[1 0 1 1 0 1 1 1]
bow of s2:
[0 1 1 0 1 1 1 1]
sim_cos(s1, s2):
0.666666666667
